'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _default2
    
    '''<summary>
    '''txtSJStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSJStartDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''imgSJStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSJStartDate As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''calexSJStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calexSJStartDate As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''txtSJEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSJEndDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''imgSJEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSJEndDate As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''calexSJEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calexSJEndDate As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''btnCalSJMetrics control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCalSJMetrics As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''dgOutstandingSJ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgOutstandingSJ As Global.System.Web.UI.WebControls.DataGrid
    
    '''<summary>
    '''chrtLineSJ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chrtLineSJ As Global.System.Web.UI.DataVisualization.Charting.Chart
    
    '''<summary>
    '''chrtPieSJ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chrtPieSJ As Global.System.Web.UI.DataVisualization.Charting.Chart
    
    '''<summary>
    '''txtTRStartingDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTRStartingDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''imgTRStartingDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgTRStartingDate As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''calexTRStartingDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calexTRStartingDate As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''txtTREndingDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTREndingDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''imgTREndingDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgTREndingDate As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''calexTREndingDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calexTREndingDate As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''btnTRMetricsCalculate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTRMetricsCalculate As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''dgOutstandingTR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgOutstandingTR As Global.System.Web.UI.WebControls.DataGrid
    
    '''<summary>
    '''chrtLineTechReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chrtLineTechReport As Global.System.Web.UI.DataVisualization.Charting.Chart
    
    '''<summary>
    '''chrtPieTechReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chrtPieTechReport As Global.System.Web.UI.DataVisualization.Charting.Chart
End Class
