'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _default7
    
    '''<summary>
    '''PageMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PageMain As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''cpe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpe As Global.AjaxControlToolkit.CollapsiblePanelExtender
    
    '''<summary>
    '''pnlClientInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlClientInfo As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblClientInfoCollapse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClientInfoCollapse As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnReturnClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReturnClient As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''txtClientID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClientID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtClientCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClientCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtClientName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClientName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtRemarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemarks As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtServiceID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtServiceID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtClSvcID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClSvcID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtServiceName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtServiceName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescription As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chkIsActiveFlg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIsActiveFlg As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cpeDevice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpeDevice As Global.AjaxControlToolkit.CollapsiblePanelExtender
    
    '''<summary>
    '''pnlDevice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDevice As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblDeviceSectionCollapse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeviceSectionCollapse As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''dgClSvcDevices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgClSvcDevices As Global.System.Web.UI.WebControls.DataGrid
    
    '''<summary>
    '''btnUnAssignedDevice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUnAssignedDevice As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnAddDevice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddDevice As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''CollapsiblePanelExtender1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CollapsiblePanelExtender1 As Global.AjaxControlToolkit.CollapsiblePanelExtender
    
    '''<summary>
    '''pnlWork control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlWork As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblWorkSectionCollapse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWorkSectionCollapse As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''dgWork control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgWork As Global.System.Web.UI.WebControls.DataGrid
    
    '''<summary>
    '''btnNewJob control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNewJob As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''CollapsiblePanelExtender2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CollapsiblePanelExtender2 As Global.AjaxControlToolkit.CollapsiblePanelExtender
    
    '''<summary>
    '''pnlTechRep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTechRep As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblTRSectionCollapse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTRSectionCollapse As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''dgTechReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgTechReports As Global.System.Web.UI.WebControls.DataGrid
    
    '''<summary>
    '''btnNewTechReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNewTechReport As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''mpDevice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpDevice As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''pnlDeviceSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDeviceSearch As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''txtSNSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSNSearch As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnSearchSN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearchSN As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''txtNameSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNameSearch As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnNameSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNameSearch As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''txtItemCodeSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtItemCodeSearch As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnItemCodeSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnItemCodeSearch As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnClearDeviceResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClearDeviceResults As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''dgResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgResults As Global.System.Web.UI.WebControls.DataGrid
    
    '''<summary>
    '''txtCLSSVCDEVID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCLSSVCDEVID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDEVID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDEVID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtITEMCODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtITEMCODE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDeviceName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDeviceName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDEVICETYPE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDEVICETYPE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSERIALNUMBER control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSERIALNUMBER As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddStatus As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chkIsAvailable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIsAvailable As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''txtIPADDRESS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIPADDRESS As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtBRANDTYPE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBRANDTYPE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtModel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtModel As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtHOSTNAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHOSTNAME As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtUSERNAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUSERNAME As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPASSWORD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPASSWORD As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtMAC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMAC As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFIRMWAREVERSION control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFIRMWAREVERSION As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDEFAULTIPADDRESS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDEFAULTIPADDRESS As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSTREAM1RESOLUTION control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSTREAM1RESOLUTION As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSTREAM1FPS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSTREAM1FPS As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnSelectDevice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSelectDevice As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancelModalDevice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelModalDevice As Global.System.Web.UI.WebControls.Button
End Class
